TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Configuration data files are installed in $(TOP)/data
DATA += ecsInitCP.pv
DATA += ecsInitMK.pv
DATA += ecsSimInit.pv
DATA += ecsInitLab.pv

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

